// libs/vortex-react/src/editor/Reader.tsx
// React parity of Reader.svelte: renders the same Tiptap JSON as static HTML.
//
// generateHTML only ever calls renderHTML, so node views are never instantiated — the inert
// factories passed here are correct (and keep this component free of node-view imports).
import { useMemo } from 'react';
import { generateHTML } from '@tiptap/core';
import type { JSONContent } from '@tiptap/core';
import { buildExtensions, type EditorNodeViews } from '@cloudvoyant/vortex-ui';

const noopNodeView = () => () => ({}) as never;
const inertNodeViews: EditorNodeViews = {
  image: noopNodeView,
  urlMention: noopNodeView,
  linkPreview: noopNodeView,
  codeBlock: noopNodeView,
};

export interface ReaderProps {
  content: string;
  className?: string;
}

export function Reader({ content, className }: ReaderProps) {
  const html = useMemo(() => {
    if (!content) return '';
    try {
      const json = JSON.parse(content) as JSONContent;
      // Strip the leading H1 — the page renders the title in its own header.
      if (json.content?.[0]?.type === 'heading' && json.content[0]?.attrs?.level === 1) {
        json.content = json.content.slice(1);
      }
      // Same extension set as the Editor, plus heading ids so headings are anchor-linkable.
      return generateHTML(json, buildExtensions({ headingWithId: true, nodeViews: inertNodeViews }));
    } catch {
      return '';
    }
  }, [content]);

  return (
    <div
      className={className ?? 'prose prose-lg reader-content max-w-none dark:prose-invert'}
      // SAFETY: the HTML is generated by Tiptap's generateHTML from the editor's OWN schema
      // (the same trust level as the Svelte reader's {@html}). It is not arbitrary user input,
      // and node renderHTML implementations escape interpolated text.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
